// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
// A chave e a URL são importadas de src/lib/supabase-config.ts para garantir
// que a nova chave publishable seja sempre usada, mesmo quando o Lovable
// regenerar este arquivo. NÃO substitua estas importações por strings hardcoded.
import { SUPABASE_URL, SUPABASE_ANON_KEY } from '@/lib/supabase-config';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
