// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL ?? "https://bskfnthwewhpfrldbhqx.supabase.co";
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ?? "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJza2ZudGh3ZXdocGZybGRiaHF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIxMjI2NzUsImV4cCI6MjA4NzY5ODY3NX0.5PDJb5LOxw5ShRjTJUjcSWt3Tw43JIV2HDkYP3rjSZQ";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
