// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bskfnthwewhpfrldbhqx.supabase.co";
// Atualizado para a nova chave publishable (sb_publishable_...) — a legacy anon key JWT foi desabilitada no projeto.
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_XlH73lxriQdgud9WSQZ6Eg_paORcfoT";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
